#!/bin/bash

apt update
apt install -y ruby screen figlet toilet cowsay lolcat boxes  > /dev/null 2>&1
toilet -w 100 Megatech | lolcat
toilet -w 82 -f mini Iniciando... | lolcat
gem install apt-spy2
clear
toilet -w 82 -f mini Iniciando... | lolcat
toilet -w 82 -f mini Instalação Zabbix | lolcat

#!INSTALAÇÃO REPOSITORIO ZABBIX
wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
dpkg -i zabbix-release_6.4-1+ubuntu22.04_all.deb
apt update
apt install zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent -y
clear

#!INSTALAÇÃO REPOSITORIO MYSQL
toilet -w 82 -f mini Iniciando... | lolcat
toilet -w 82 -f mini Instalação MYSQL | lolcat
mysql -uroot -p
