#!/bin/bash

apt update
apt install -y ruby screen figlet toilet cowsay lolcat boxes  > /dev/null 2>&1
toilet -w 100 Megatech | lolcat
toilet -w 82 -f mini Iniciando... | lolcat
gem install apt-spy2
clear
toilet -w 82 -f mini Iniciando... | lolcat
toilet -w 82 -f mini Instalação Zabbix | lolcat

#!INSTALAÇÃO REPOSITORIO ZABBIX
wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
dpkg -i zabbix-release_6.4-1+ubuntu22.04_all.deb
apt update
apt install -y zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent -y
apt install -y locales   > /dev/null 2>&1
locale-gen pt_BR.UTF-8 
m-a prepare 

#!INSTALAÇÃO REPOSITORIO MYSQL
toilet -w 82 -f mini Iniciando... | lolcat
toilet -w 82 -f mini Instalação MYSQL | lolcat
sudo mysql -u root -e "create database zabbix character set utf8mb4 collate utf8mb4_bin"
sudo mysql -u root -e "create user zabbix@localhost identified by 'password'"
sudo mysql -u root -e "grant all privileges on zabbix.* to zabbix@localhost"
sudo mysql -u root -e "set global log_bin_trust_function_creators = 1"

echo "This password is the zabbix user password for the database"
sudo zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p megatech

sudo mysql -u root -e "set global log_bin_trust_function_creators = 0"

sudo sed -i 's/# DBPassword=megatech/DBPassword=megatech/g' /etc/zabbix/zabbix_server.conf

sudo systemctl restart zabbix-server zabbix-agent apache2
sudo systemctl enable zabbix-server zabbix-agent apache2

#!INSTALAÇÃO REPOSITORIO GRAFANA
toilet -w 82 -f mini Iniciando... | lolcat
toilet -w 82 -f mini Instalação GRAFANA | lolcat
sudo apt-get install -y adduser libfontconfig1 musl
wget https://dl.grafana.com/enterprise/release/grafana-enterprise_9.5.9_amd64.deb
sudo dpkg -i grafana-enterprise_9.5.9_amd64.deb
systemctl restart zabbix-server zabbix-agent apache2 grafana-server

#FIX CACHESIZE
#sed s/'# CacheSize=8M'/'CacheSize=16M'/g -i /etc/zabbix/zabbix_server.conf
systemctl enable zabbix-server zabbix-agent apache2 grafana-server
systemctl restart zabbix-server zabbix-agent apache2 grafana-server
cat <<'EOF' >> ~/.bashrc
shopt -s histappend
HISTFILESIZE=1000000
HISTSIZE=1000000
HISTCONTROL=ignoreboth
HISTIGNORE='history'
HISTTIMEFORMAT='%F %T '
shopt -s cmdhist
PROMPT_COMMAND='history -a
